[versions]
activity-ktx = "1.7.2"
appcompat = "1.6.1"
coil = "2.4.0"
converter-gson = "2.9.0"
datastore-preferences = "1.0.0"
fragment-ktx = "1.6.0"
core-ktx = "1.10.1"
gson = "2.10.1"
kotlinx-coroutines-android = "1.7.1"
lifecycle = "2.6.1"
logging-interceptor = "4.11.0"
navigation-fragment-ktx = "2.6.0"
navigation-ui-ktx = "2.6.0"
okhttp = "4.11.0"
preference-ktx = "1.2.0"
retrofit = "2.9.0"
room = "2.5.2"
security-crypto-ktx = "1.1.0-alpha06"
startup-runtime = "1.1.1"
timber = "5.0.1"
webkit = "1.7.0"
work-runtime-ktx = "2.8.1"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-android" }

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "security-crypto-ktx" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }

[plugins]

[bundles]
android-base = ["core-ktx", "appcompat", "activity-ktx", "fragment-ktx"]

